export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const TITLE_CHANGED = 'TITLE_CHANGED';

export const REQUEST_PICTURE = 'REQUEST_PICTURE';
export const PUSH_BACK_PICTURE = 'PUSH_BACK_PICTURE';
export const RECEIVE_PICTURE = 'RECEIVE_PICTURE';
