export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const TITLE_CHANGED = 'TITLE_CHANGED';

export const REQUEST_PICTURE = 'REQUEST_PICTURE';
export const PUSH_BACK_PICTURE = 'PUSH_BACK_PICTURE';
export const RECEIVE_PICTURE = 'RECEIVE_PICTURE';
export const SET_TITLE = 'SET_TITLE';
export const SET_PARAGRAPHS = 'SET_PARAGRAPHS';
export const SET_HREF = 'SET_HREF';
export const SET_LINK_TEXT = 'SET_LINK_TEXT';
